user_user_homepage:
    path:     /
    defaults: { _controller: UserUserBundle:User:login }

user_dashboard:
    path: /dashboard
    defaults: { _controller: AsseterDashboardBundle:Asseter:index }

user_register:
    path:     /register
    defaults: { _controller: UserUserBundle:User:register }

user_register_submit:
    path:    /register/user
    defaults: { _controller: UserUserBundle:User:registerUser }