parameters:
#    user_user.example.class: User\UserBundle\Example

services:
#    user_user.example:
#        class: %user_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
